- name: Deploy AIQUM OVA for DHCP tasks.
  no_log: true
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ vc_hostname }}"
    username: "{{ vc_username }}"
    password: "{{ vc_password }}"
    validate_certs: no
    ovf: "{{ ovf_path }}"
    networks: {"nat": '{{vm_network}}'}
    cluster: "{{ vc_cluster_name }}"
    datacenter: "{{ datacenter_name }}"
    datastore: "{{ datastore_name }}"
    name: "{{ aiqum_vm_name }}"
    power_on: yes
    wait_for_ip_address: false
    allow_duplicates: no
    inject_ovf_env: yes
    properties:
             org.linuxdistx.HostFQDN: '{{ aiqum_vm_name }}.{{ domain_name }}'
  delegate_to: localhost
  tags:
    - deploy_ova_dhcp_ip

- name: You have 15 minutes to log into the VMWare console for this VM and to answer the timezone questions and to create the new admin user and password.
  pause:
    minutes: 15
  tags:
    - deploy_ova_dhcp_ip

- name: Get VM MAC address to gather DHCP IP in later tasks.
  no_log: true
  block:
    - name: Get VM MAC address and create a variable for DHCP IP to be used later. 
      community.vmware.vmware_vm_info:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_password }}"
        validate_certs: no
        vm_type: vm
        show_attribute: no
      delegate_to: localhost
      register: vm_info
    - set_fact:
        get_mac: "{{ item.mac_address[0] }}"
      with_items:
        - "{{ vm_info.virtual_machines | json_query(query) }}"
      vars:
        query: "[?guest_name=='{{ aiqum_vm_name }}']"
  tags:
    - deploy_ova_dhcp_ip
    - guest_facts
    - get_mac

- name: Get DHCP of AIQUM VM.
  set_fact:
    dhcp_ip: "{{ item.vm_network[get_mac].ipv4[0] }}"
  with_items:
    - "{{ vm_info.virtual_machines | json_query(query) }}"
  vars:
    query: "[?guest_name== '{{ aiqum_vm_name }}' ]"
  tags:
    - deploy_ova_dhcp_ip
    - guest_facts
    - get_dhcp

- name: Add an ONTAP cluster to AIQUM for DHCP tasks.
  no_log: true
  aiqum_clusters:
    state: present
    hostip: "{{ dhcp_ip }}"
    port: '{{ aiqumport }}'
    user: '{{ aiqumuser }}'
    password: '{{ aiqumpassword }}'
    cluster_address: '{{ ontap_cluster_address }}'
    cluster_username: '{{ ontap_cluster_username }}'
    cluster_password: '{{ ontap_cluster_password }}'
    cluster_protocol: '{{ cluster_protocol }}'
    cluster_port: '{{ cluster_port }}'
  retries: 10
  delay: 60
  register: result
  until: result is succeeded
  tags:
    - deploy_ova_dhcp_ip
    - get_vm_properties
    - guest_facts
