- name: Import AIQUM OVA and deploy with static IP. 
  no_log: true
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ vc_hostname }}"
    username: "{{ vc_username }}"
    password: "{{ vc_password }}"
    validate_certs: no
    ovf: "{{ ovf_path }}"
    networks: {"nat": '{{vm_network}}'}
    cluster: "{{ vc_cluster_name }}"
    datacenter: "{{ datacenter_name }}"
    datastore: "{{ datastore_name }}"
    name: "{{ aiqum_vm_name }}"
    power_on: yes
    wait_for_ip_address: false
    allow_duplicates: no
    inject_ovf_env: yes
    properties:
             org.linuxdistx.Gateway: '{{ aiqum_gateway }}'
             org.linuxdistx.HostFQDN: '{{ aiqum_vm_name }}.{{ domain_name }}'
             org.linuxdistx.IPAddress: '{{ aiqum_ipaddress }}'
             org.linuxdistx.NetworkMask: '{{ aiqum_netmask }}'
             org.linuxdistx.PrimaryDNS: '{{ primaryDNS }}'
             org.linuxdistx.SecondaryDNS: '{{ secondaryDNS }}'
  delegate_to: localhost
  tags:
    - deploy_ova_static_ip

- name: Pause for 15 minutes for Network service to start.
  pause:
    minutes: 15
  tags:
    - deploy_ova_static_ip

- name: Add an ONTAP cluster to AIQUM.
  no_log: true
  aiqum_clusters:
    state: present
    hostip: '{{ aiqum_ipaddress }}'
    port: '{{ aiqumport }}'
    user: '{{ aiqumuser }}'
    password: '{{ aiqumpassword }}'
    cluster_address: '{{ ontap_cluster_address }}'
    cluster_username: '{{ ontap_cluster_username }}'
    cluster_password: '{{ ontap_cluster_password }}'
    cluster_protocol: '{{ cluster_protocol }}'
    cluster_port: '{{ cluster_port }}'
  retries: 10
  delay: 60
  register: result
  until: result is succeeded
  tags:
    - deploy_ova_static_ip
    - aiqum_cluster
